### ISSUE TITLE
@deriveTraverse annotation should support sealed trait families

### ISSUE THREAD

**Issue by rlmark** [andyscott/droste#100]
Currently, the `deriveTraverse` annotation supports sealed trait hierarchies whose members do not reference other sealed trait hierarchies, but it would be nice for the `deriveTraverse` annotation to support a structure like this: 

```
sealed trait TreeF[A]

sealed trait FieldF[A] 

object TreeF {
  final case class NamedField[A](fieldName: String, tpe: A) extends FieldF[A]
  final case class NumberedField[A](fieldNumber: Int, tpe: A) extends FieldF[A]

  final case class BranchF[A](left: A, right: A) extends TreeF[A]
  final case class NodeF[A](name: String, a: FieldF2[A]) extends TreeF[A]
}
```
Where TreeF's Node class contains a field which is itself a member of another sealed trait, FieldF. 

I've written a minimal reproduction of this request [here](https://github.com/rlmark/RecursionSchemeSandbox/tree/master/src/main/scala/derive_traverse). With the `Playground` class file being the entry point showing the difference in behavior between the `deriveTraverse` macro and a manually written `Traverse` instance.

**Comment by andyscott** [comment]
Seems very reasonable. I'd be happy to merge a PR improving support for `@deriveTraverse` 😄.

**Comment by andyscott** [comment]
I'll just assign both of you. Just in case!

**Comment by pepegar** [comment]
I think we can close this one? feel free to re-open in case you feel we should address something else
