### ISSUE TITLE
Recursion scheme friendly names for Free/Cofree and pattern functors

### ISSUE THREAD

**Issue by andyscott** [andyscott/droste#56]
I've been considering a rename of Free/Cofree and CoenvT/EnvT.

- Cofree/EnvT to Attr/AttrF
- Free/CoenvT to Coattr/CoattrF

The documentation for these items would still note that they are Free, Cofree, etc. The main motivation is to reduce the cognitive overhead. The "Attr" name for attributing/annotating trees shows up in existing recursion scheme documentation (such as https://blog.sumtypeofway.com/recursion-schemes-part-iv-time-is-of-the-essence/), so the name isn't new. Remembering the pattern functor for Cofree & Free could be easy, but right now you have to be aware of EnvT and CoenvT.

What do others think?

**Comment by AdrianRaFo** [comment]
Sorry `Cofree` is `Attr and `Free` is `Coattr`? Looks like it should be the opposite.

**Comment by pepegar** [comment]
:+1: to the rename!
