### ISSUE TITLE
Remove kittens dependency; add custom macro for Traverse instances

### ISSUE THREAD

**Issue by andyscott** [andyscott/droste#57]
😄

**Comment by pepegar** [comment]
I'd prefer to use the same `@deriveFixedpoint` macro and substitute the `Functor` instance with a `traversable` one.

**Comment by andyscott** [comment]
I thought Kittens doesn't support `Traversable`? So won't we need to write our own implementation to derive those instances?

**Comment by pepegar** [comment]
Yeah, it doesn't support deriving `Traversable`, we'd need to implement derivation ourselves.  What I meant is that we wouldn't need a new macro right? or you mean that we should provide a macro annotation just for deriving the instance of a fixed point data type?
